layout(local_size_x=WORKGROUP_SIZE_X,local_size_y=WORKGROUP_SIZE_Y)in;

layout(binding=0, rgba8ui) uniform uimage2D tex;

uniform bool noise;

ivec4 hash(ivec2 id){
	return ivec4((id.x*id.y*1103515245+12345)&0xFF,
				(id.x*id.y*1103515245+12345)&0xFF,
				(id.y*id.y*1103515245+12345)&0xFF,
				(id.y*id.x*1103515245+12345)&0xFF);
};

void main(){
	ivec2 itc = ivec2(gl_GlobalInvocationID.xy);
#ifdef NOISE
	ivec4 color = hash(itc);
#else
	ivec4 color = ivec4(0,0,0,0);
#endif
	imageStore(tex,itc,color);
}
